export const CHESS_PIECE_PAWN = "PAWN";
export const CHESS_PIECE_KNIGHT = "KNIGHT";
export const CHESS_PIECE_ROOK = "ROOK";
export const CHESS_PIECE_BISHOP = "BISHOP";
export const CHESS_PIECE_QUEEN = "QUEEN";
export const CHESS_PIECE_KING = "KING";

export const ALL_CHESS_PIECES = [CHESS_PIECE_PAWN, CHESS_PIECE_KNIGHT, CHESS_PIECE_ROOK, CHESS_PIECE_BISHOP, CHESS_PIECE_QUEEN, CHESS_PIECE_KING];

export const CHESS_SIDE_WHITE = "WHITE";
export const CHESS_SIDE_BLACK = "BLACK";